### PR TITLE
[Config] Define BOOST_HANA_CONFIG_CLANG for apple clang

### PR DESCRIPTION
**Pull request by KholdStare**
Hi!

I had trouble building the library with the version of clang that came with Xcode, and it came down to the configuration thinking I was using GCC. Using `__apple_build_version__` to map to the proper clang build version fixed the problems. See https://gist.github.com/yamaya/2924292 for version reference.

Thank you!
Alex.

### CODE REVIEW

**Comment by ldionne** [comment]
Can you please show me your `clang++ --version`? Mine completely fails to build Hana (compilation errors and then ICEs when I fix the compilation errors).

Here's my `clang++ --version`:
```shell
> clang++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by KholdStare** [comment]
Thanks for taking a look.

Here is my `clang++ --version` (I updated Xcode on OS X Yosemite):
```
> clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

Note that I actually had to also specify a path for libc++ when running cmake: 

`cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang -DLIBCXX_ROOT=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/`

**Comment by ldionne** [comment]
I'm on Mavericks with Xcode 6.2, and I can tell that the associated Clang isn't able to compile Hana. However, it works on your Xcode 6.3.2 (the latest on Yosemite). Based on [the Xcode/Clang version record you linked above](https://gist.github.com/yamaya/2924292), it would be nice to know whether Xcode 6.3 and 6.3.1 are able to compile Hana too, which would give us the minimal required version of Xcode.

**Comment by ldionne** [comment]
I tweaked your PR in 66c0b70; do you agree with my approach? Also, could you please build 66c0b70 with your Xcode just to make sure it actually works. Of course, I'll get my hands on a more recent version of Xcode to make sure it works on the long term, but for now I don't have that.

**Comment by KholdStare** [comment]
It looks good to me, and everything compiles. Thank you! :smiley:

**Comment by ldionne** [comment]
Thanks for the feedback and the PR! This issue will be closed automatically when I merge the changes to master, which I will do as soon as https://travis-ci.org/ldionne/hana/builds/64145010 passes. Thanks!
